name: Run Daily News Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:     # Allow manual trigger from GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit changes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the full pipeline
        run: |
          python pipeline.py

      - name: Commit and push updated JSONs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/articles.json data/articles_clustered.json
          git commit -m "🔄 Update clustered news via daily pipeline" || echo "No changes to commit"
          git push